pub mod context;
pub mod error;
pub mod memory;
pub mod message;
pub mod model;
pub mod prompt;
pub mod resource;
pub mod run;
pub mod session;
pub mod stream;
pub mod tool;
pub mod usage;

pub use context::*;
pub use error::*;
pub use memory::*;
pub use message::*;
pub use model::*;
pub use prompt::*;
pub use resource::*;
pub use run::*;
pub use session::*;
pub use stream::*;
pub use tool::*;
pub use usage::*;

pub const AGENT_RUN_PROTOCOL: &str = "mutsuki.agent/run@1";
pub const AGENT_LOOP_STEP_PROTOCOL: &str = "mutsuki.agent.loop/step@1";
pub const AGENT_CONTEXT_BUILD_PROTOCOL: &str = "mutsuki.agent.context/build@1";
pub const AGENT_TOOL_LIST_PROTOCOL: &str = "mutsuki.agent.tool/list@1";
pub const AGENT_TOOL_EXECUTE_PROTOCOL: &str = "mutsuki.agent.tool/execute@1";
pub const AGENT_SESSION_CREATE_PROTOCOL: &str = "mutsuki.agent.session/create@1";
pub const AGENT_SESSION_GET_PROTOCOL: &str = "mutsuki.agent.session/get@1";
pub const AGENT_SESSION_APPEND_PROTOCOL: &str = "mutsuki.agent.session/append@1";
pub const AGENT_SESSION_SNAPSHOT_PROTOCOL: &str = "mutsuki.agent.session/snapshot@1";
pub const AGENT_MEMORY_QUERY_PROTOCOL: &str = "mutsuki.agent.memory/query@1";
pub const AGENT_MEMORY_WRITE_PROTOCOL: &str = "mutsuki.agent.memory/write@1";
pub const AGENT_MEMORY_ACTIVATE_PROTOCOL: &str = "mutsuki.agent.memory/activate@1";
pub const AGENT_MODEL_GENERATE_PROTOCOL: &str = "mutsuki.agent.model/generate@1";
pub const AGENT_MODEL_STREAM_PROTOCOL: &str = "mutsuki.agent.model/stream@1";
pub const AGENT_PROMPT_RENDER_PROTOCOL: &str = "mutsuki.agent.prompt/render@1";
pub const AGENT_PROMPT_GET_PROTOCOL: &str = "mutsuki.agent.prompt/get@1";
